### ISSUE TITLE
Slug name needs changing

### ISSUE THREAD

**Issue by SteveRussell33** [mlaban64/STS-Free#1]
I suggest changing the slug name to something like ``STS-Free`` so as not to clash with an older module collection called ``STS``

**Comment by mlaban64** [comment]
Hi Steve,
 
Thanks for your feedback. Andrew Belt and cschol recommended to use STS as slug , so that is what I did in the new release...it has now been given a status as plugin by Andrew Belt, so I hope it will be released soon...
 
I did not find any historical collection called STS, but I might have overlooked it...Can you point out what older collection you are referring to?
 
Thanks, and regards,
Marinko

**Comment by SteveRussell33** [comment]
This is the collection I was referring to: https://library.vcvrack.com/STS I know it does say the current version is 1.1.2 which shows it wasn't officially updated to Rack v2.
The repo @ https://github.com/SmallTownSound was open-source for a while until the owner deleted it. So it was an unofficial v2 release within the community.

Hope that explains the issue, but of course I'll leave the decision to you.

Kind Regards
Steve

**Comment by mlaban64** [comment]
Hi Steve,
 
Thanks for the feedback...I've asked Andrew Belt what he recommends, as this may lead indeed to confusion or even branding/copyright issues...Don't want to step on any toes :-)
 
Regards,
Marinko

**Comment by mlaban64** [comment]
Hi @SteveRussell33 , after consulting with Andrew Belt and cshol, their recommendation was to change the slug to 
SmarTAZZStudio-Free, so I've uploaded a new .json accordingly.

Thanks again for highlighting this!

**Comment by SteveRussell33** [comment]
Hi [Marinko](https://github.com/mlaban64)

Glad to hear this has been resolved successfully. I'll now close this issue as complete.

Kind Regards
Steve
